name: suzano-cypress-tests-API
# Executa os testes do Cypress em paralelo e publica os relatórios individuais
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]
        include:
          - containers: 1
            spec: cypress/e2e/api/products/get.spec.js
          - containers: 2
            spec: cypress/e2e/api/products/post.spec.js
          - containers: 3
            spec: cypress/e2e/api/products/update.spec.js
          - containers: 4
            spec: cypress/e2e/api/products/delete.spec.js
          - containers: 5
            spec: cypress/e2e/api/products/negative.spec.js
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Instalar dependências
        run: npm ci
      
      - name: Executar testes do Cypress
        run: npx cypress run --spec ${{ matrix.spec }} --reporter cypress-mochawesome-reporter
      
      - name: Salvar relatórios como artefatos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results-${{ matrix.containers }}
          path: |
            cypress/reports/**/*
          retention-days: 10
          if-no-files-found: warn

  publish-pages:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
      
      - name: Criar diretório para publicação
        run: mkdir -p pages-content
      
      - name: Baixar todos os artefatos
        uses: actions/download-artifact@v4
        with:
          pattern: cypress-results-*
          path: artefatos-baixados
      
      - name: Preparar conteúdo para GitHub Pages
        run: |
          # Copiar conteúdo dos artefatos para a pasta de publicação
          cp -r artefatos-baixados/* pages-content/
          
          # Criar um index.html simples que lista os relatórios
          echo '<!DOCTYPE html>
          <html>
          <head>
            <title>Relatórios de Testes Cypress</title>
            <style>
              body { font-family: Arial, sans-serif; margin: 20px; }
              h1 { color: #333; }
              .container { display: flex; flex-wrap: wrap; }
              .report-card { 
                border: 1px solid #ddd; 
                border-radius: 8px; 
                padding: 15px; 
                margin: 10px; 
                width: 200px;
                background-color: #f9f9f9;
              }
              .report-card h2 { margin-top: 0; font-size: 18px; }
              .report-card a { 
                display: inline-block; 
                margin-top: 10px; 
                color: #fff;
                background-color: #0366d6;
                text-decoration: none;
                padding: 8px 16px;
                border-radius: 4px;
              }
              .report-card a:hover { background-color: #0056b3; }
            </style>
          </head>
          <body>
            <h1>Relatórios de Testes Cypress</h1>
            <div class="container">
              <div class="report-card">
                <h2>GET Tests</h2>
                <p>Consultas de produtos</p>
                <a href="cypress-results-1/cypress/reports/html/index.html">Ver Relatório</a>
              </div>
              <div class="report-card">
                <h2>POST Tests</h2>
                <p>Criação de produtos</p>
                <a href="cypress-results-2/cypress/reports/html/index.html">Ver Relatório</a>
              </div>
              <div class="report-card">
                <h2>UPDATE Tests</h2>
                <p>Atualização de produtos</p>
                <a href="cypress-results-3/cypress/reports/html/index.html">Ver Relatório</a>
              </div>
              <div class="report-card">
                <h2>DELETE Tests</h2>
                <p>Remoção de produtos</p>
                <a href="cypress-results-4/cypress/reports/html/index.html">Ver Relatório</a>
              </div>
              <div class="report-card">
                <h2>Negative Tests</h2>
                <p>Testes negativos</p>
                <a href="cypress-results-5/cypress/reports/html/index.html">Ver Relatório</a>
              </div>
            </div>
          </body>
          </html>' > pages-content/index.html
          
          # Verificar conteúdo gerado
          find pages-content -type f | sort
      
      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: pages-content
          publish_branch: gh-pages
