name: suzano-cypress-tests-API
# Executa os testes do Cypress e gera relatório consolidado
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]
        include:
          - containers: 1
            spec: cypress/e2e/api/products/get.spec.js
          - containers: 2
            spec: cypress/e2e/api/products/post.spec.js
          - containers: 3
            spec: cypress/e2e/api/products/update.spec.js
          - containers: 4
            spec: cypress/e2e/api/products/delete.spec.js
          - containers: 5
            spec: cypress/e2e/api/products/negative.spec.js
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes do Cypress com relatório
        uses: cypress-io/github-action@v5
        with:
          spec: ${{ matrix.spec }}
          browser: electron
          headed: false

      # Debug - verificar o que foi gerado
      - name: Verificar arquivos de relatório gerados
        if: always()
        run: |
          echo "Conteúdo de cypress/reports:"
          find cypress/reports -type f | sort

      - name: Salvar relatórios como artefatos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results-${{ matrix.containers }}
          path: |
            cypress/reports/**
            cypress/screenshots/**
          retention-days: 5

  generate-report:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm ci

      - name: Baixar todos os relatórios
        uses: actions/download-artifact@v4
        with:
          path: cypress-results

      # Debug - verificar o que foi baixado
      - name: Verificar estrutura de artefatos baixados
        run: |
          echo "Estrutura de diretórios dos artefatos:"
          find cypress-results -type f | sort

      - name: Preparar diretório de relatórios
        run: |
          mkdir -p cypress/reports/html/.jsons
          
          # Localizar todos os arquivos JSON, independentemente da estrutura
          find cypress-results -name "*.json" -exec cp {} cypress/reports/html/.jsons/ \; || echo "Nenhum arquivo JSON encontrado"
          
          echo "Arquivos JSON encontrados:"
          ls -la cypress/reports/html/.jsons/ || echo "Diretório vazio ou inexistente"

      - name: Gerar relatório consolidado
        run: |
          npm i -g mochawesome-merge mochawesome-report-generator
          
          if [ "$(find cypress/reports/html/.jsons/ -name '*.json' | wc -l)" -gt 0 ]; then
            echo "Arquivos JSON encontrados, gerando relatório consolidado"
            mochawesome-merge cypress/reports/html/.jsons/*.json > cypress/reports/merged-report.json
            marge cypress/reports/merged-report.json -f index -o cypress/reports/final
          else
            echo "Nenhum arquivo JSON encontrado para mesclar. Criando relatório vazio."
            echo '{"results":[],"stats":{"suites":0,"tests":0,"passes":0,"failures":0,"pending":0}}' > cypress/reports/merged-report.json
            marge cypress/reports/merged-report.json -f index -o cypress/reports/final
          fi

      - name: Publicar relatório final
        uses: actions/upload-artifact@v4
        with:
          name: final-report
          path: cypress/reports/final
          retention-days: 10
