name: suzano-cypress-tests-API
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]
        include:
          - containers: 1
            spec: cypress/e2e/api/products/get.spec.js
          - containers: 2
            spec: cypress/e2e/api/products/post.spec.js
          - containers: 3
            spec: cypress/e2e/api/products/update.spec.js
          - containers: 4
            spec: cypress/e2e/api/products/delete.spec.js
          - containers: 5
            spec: cypress/e2e/api/products/negative.spec.js
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Instalar dependências
        run: npm ci
      
      - name: Executar testes do Cypress
        run: npx cypress run --spec ${{ matrix.spec }} --reporter cypress-mochawesome-reporter
      
      - name: Verificar arquivos gerados
        if: always()
        run: |
          echo "Arquivos em cypress/reports:"
          find cypress/reports -type f | sort || echo "Diretório não encontrado"
      
      - name: Salvar relatórios como artefatos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results-${{ matrix.containers }}
          path: |
            cypress/reports/**/*
          retention-days: 5
          if-no-files-found: warn

  publish-to-pages:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Baixar todos os artefatos
        uses: actions/download-artifact@v4
        with:
          path: relatorios-baixados
      
      - name: Verificar estrutura dos artefatos
        run: |
          echo "Estrutura completa dos artefatos:"
          find relatorios-baixados -type f | grep -E 'html|htm|json' || echo "Nenhum HTML/JSON encontrado"
      
      - name: Preparar diretório para GitHub Pages
        run: |
          # Criar estrutura de diretórios para o site
          mkdir -p site
          
          # Criar página índice principal
          cat > site/index.html <<EOL
          <!DOCTYPE html>
          <html lang="pt-BR">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Relatórios de Testes API - Suzano QA Challenge</title>
              <style>
                  body { font-family: Arial, sans-serif; line-height: 1.6; margin: 0; padding: 20px; color: #333; }
                  h1 { color: #2c3e50; border-bottom: 2px solid #eee; padding-bottom: 10px; }
                  .container { max-width: 1200px; margin: 0 auto; }
                  .report-list { display: grid; grid-template-columns: repeat(auto-fill, minmax(250px, 1fr)); gap: 20px; margin-top: 20px; }
                  .report-card { border: 1px solid #ddd; border-radius: 8px; padding: 15px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
                  .report-card h2 { margin-top: 0; color: #3498db; }
                  a { color: #3498db; text-decoration: none; }
                  a:hover { text-decoration: underline; }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>Relatórios de Testes API - Suzano QA Challenge</h1>
                  
                  <p>Selecione um dos relatórios abaixo para visualizar os resultados dos testes:</p>
                  
                  <div class="report-list">
                      <div class="report-card">
                          <h2>Relatório 1 - GET Products</h2>
                          <p>Testes de consulta de produtos da API</p>
                          <a href="./relatorio-1/">Ver Relatório</a>
                      </div>
                      <div class="report-card">
                          <h2>Relatório 2 - POST Products</h2>
                          <p>Testes de criação de produtos</p>
                          <a href="./relatorio-2/">Ver Relatório</a>
                      </div>
                      <div class="report-card">
                          <h2>Relatório 3 - UPDATE Products</h2>
                          <p>Testes de atualização de produtos</p>
                          <a href="./relatorio-3/">Ver Relatório</a>
                      </div>
                      <div class="report-card">
                          <h2>Relatório 4 - DELETE Products</h2>
                          <p>Testes de exclusão de produtos</p>
                          <a href="./relatorio-4/">Ver Relatório</a>
                      </div>
                      <div class="report-card">
                          <h2>Relatório 5 - Negative Tests</h2>
                          <p>Testes de cenários negativos</p>
                          <a href="./relatorio-5/">Ver Relatório</a>
                      </div>
                  </div>
              </div>
          </body>
          </html>
          EOL
          
          # Criar diretórios para cada relatório e copiar os conteúdos
          for i in {1..5}; do
            mkdir -p site/relatorio-$i
            
            # Copiar todo o conteúdo do relatório para o diretório respectivo
            cp -R relatorios-baixados/cypress-results-$i/cypress/reports/html/* site/relatorio-$i/ 2>/dev/null || echo "Não encontrado em reports/html"
            
            # Tentar outros caminhos possíveis
            cp -R relatorios-baixados/cypress-results-$i/cypress/reports/* site/relatorio-$i/ 2>/dev/null || echo "Não encontrado em reports"
            
            # Procurar recursivamente por arquivos HTML e copiá-los
            find relatorios-baixados/cypress-results-$i -name "*.html" -exec cp {} site/relatorio-$i/ \; 2>/dev/null || echo "Nenhum HTML encontrado"
            
            # Se o index.html não existir, criar um arquivo padrão
            if [ ! -f site/relatorio-$i/index.html ]; then
              echo "<html><body><h1>Relatório $i</h1><p>Nenhum relatório HTML foi encontrado para este teste.</p></body></html>" > site/relatorio-$i/index.html
            fi
          done
          
          # Verificar estrutura final
          echo "Estrutura final do site:"
          find site -type f | sort
      
      - name: Deploy no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          force_orphan: true
