name: suzano-cypress-tests-API
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    # Mantém os testes como estão...

  publish-to-pages:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Baixar todos os artefatos
        uses: actions/download-artifact@v4
        with:
          path: relatorios-baixados
      
      # Adiciona debugging para verificar a estrutura real dos arquivos baixados
      - name: Verificar estrutura dos artefatos
        run: |
          echo "Estrutura completa dos artefatos:"
          find relatorios-baixados -type f | grep -E 'html|htm|json' || echo "Nenhum HTML/JSON encontrado"
      
      - name: Preparar diretório para GitHub Pages
        run: |
          # Criar estrutura de diretórios para o site
          mkdir -p site
          
          # Verificar e copiar os arquivos HTML encontrados
          find relatorios-baixados -name "index.html" -exec cp -v {} site/ \;
          
          # Criar página índice principal
          cat > site/index.html <<EOL
          <!DOCTYPE html>
          <html lang="pt-BR">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Relatórios de Testes API - Suzano</title>
              <style>
                  body { font-family: Arial, sans-serif; line-height: 1.6; margin: 0; padding: 20px; color: #333; }
                  h1 { color: #2c3e50; border-bottom: 2px solid #eee; padding-bottom: 10px; }
                  .container { max-width: 1200px; margin: 0 auto; }
                  .report-list { display: grid; grid-template-columns: repeat(auto-fill, minmax(250px, 1fr)); gap: 20px; margin-top: 20px; }
                  .report-card { border: 1px solid #ddd; border-radius: 8px; padding: 15px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
                  .report-card h2 { margin-top: 0; color: #3498db; }
                  a { color: #3498db; text-decoration: none; }
                  a:hover { text-decoration: underline; }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>Relatórios de Testes API - Suzano QA Challenge</h1>
                  
                  <p>Selecione um dos relatórios abaixo para visualizar os resultados dos testes:</p>
                  
                  <div class="report-list">
                      <div class="report-card">
                          <h2>Relatório 1 - GET Products</h2>
                          <p>Testes de consulta de produtos da API</p>
                          <a href="./relatorio-1/">Ver Relatório</a>
                      </div>
                      <div class="report-card">
                          <h2>Relatório 2 - POST Products</h2>
                          <p>Testes de criação de produtos</p>
                          <a href="./relatorio-2/">Ver Relatório</a>
                      </div>
                      <div class="report-card">
                          <h2>Relatório 3 - UPDATE Products</h2>
                          <p>Testes de atualização de produtos</p>
                          <a href="./relatorio-3/">Ver Relatório</a>
                      </div>
                      <div class="report-card">
                          <h2>Relatório 4 - DELETE Products</h2>
                          <p>Testes de exclusão de produtos</p>
                          <a href="./relatorio-4/">Ver Relatório</a>
                      </div>
                      <div class="report-card">
                          <h2>Relatório 5 - Negative Tests</h2>
                          <p>Testes de cenários negativos</p>
                          <a href="./relatorio-5/">Ver Relatório</a>
                      </div>
                  </div>
              </div>
          </body>
          </html>
          EOL
          
          # Criar diretórios para cada relatório e copiar os conteúdos
          for i in {1..5}; do
            mkdir -p site/relatorio-$i
            
            # Copiar conteúdos para diretório específico (usando find para localizar os arquivos)
            find relatorios-baixados/cypress-results-$i -type f -exec cp -v {} site/relatorio-$i/ \; || echo "Nenhum arquivo encontrado para relatório $i"
            
            # Se encontrou um relatório HTML neste diretório, copie-o como index.html
            find relatorios-baixados/cypress-results-$i -name "*.html" -exec cp -v {} site/relatorio-$i/index.html \; || echo "Nenhum HTML encontrado para relatório $i"
          done
          
          # Verificar estrutura final
          echo "Estrutura final do site:"
          find site -type f | sort
      
      # Publicar no GitHub Pages
      - name: Deploy no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          force_orphan: true
