name: suzano-cypress-tests-API
# Executa os testes do Cypress e gera relatórios simples
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]
        include:
          - containers: 1
            spec: cypress/e2e/api/products/get.spec.js
          - containers: 2
            spec: cypress/e2e/api/products/post.spec.js
          - containers: 3
            spec: cypress/e2e/api/products/update.spec.js
          - containers: 4
            spec: cypress/e2e/api/products/delete.spec.js
          - containers: 5
            spec: cypress/e2e/api/products/negative.spec.js
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Instalar dependências
        run: npm ci
      
      - name: Executar testes do Cypress com relatório
        uses: cypress-io/github-action@v5
        with:
          spec: ${{ matrix.spec }}
          browser: electron
          headed: false
      
      - name: Salvar relatórios como artefatos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results-${{ matrix.containers }}
          path: |
            cypress/videos/**
            cypress/screenshots/**
            cypress/results/**
            mochawesome-report/**
          retention-days: 5
