name: suzano-cypress-tests-API
# Executa os testes do Cypress e gera relatório consolidado
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]
        include:
          - containers: 1
            spec: cypress/e2e/api/products/get.spec.js
          - containers: 2
            spec: cypress/e2e/api/products/post.spec.js
          - containers: 3
            spec: cypress/e2e/api/products/update.spec.js
          - containers: 4
            spec: cypress/e2e/api/products/delete.spec.js
          - containers: 5
            spec: cypress/e2e/api/products/negative.spec.js
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm ci

      - name: Preparar diretórios para relatórios
        run: |
          mkdir -p cypress/reports/html/.jsons
          mkdir -p cypress/reports/final

      - name: Executar testes do Cypress com relatório
        uses: cypress-io/github-action@v5
        with:
          spec: ${{ matrix.spec }}
          browser: electron
          headed: false

      - name: Salvar relatórios como artefatos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results-${{ matrix.containers }}
          path: |
            cypress/reports/html/**
            cypress/screenshots/**
          retention-days: 5

  # Job adicional para gerar relatório consolidado
  generate-report:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm ci

      - name: Baixar todos os relatórios
        uses: actions/download-artifact@v3
        with:
          path: cypress-results

      - name: Preparar diretório de relatórios
        run: |
          mkdir -p cypress/reports/html/.jsons
          find cypress-results -name "*.json" -exec cp {} cypress/reports/html/.jsons/ \;

      - name: Gerar relatório consolidado
        run: |
          npm i -g mochawesome-merge mochawesome-report-generator
          mochawesome-merge cypress/reports/html/.jsons/*.json > cypress/reports/merged-report.json
          marge cypress/reports/merged-report.json -f index -o cypress/reports/final

      - name: Publicar relatório final
        uses: actions/upload-artifact@v4
        with:
          name: final-report
          path: cypress/reports/final
          retention-days: 10
