name: suzano-cypress-tests-API
# Descrição: Executa os testes do Cypress em containers paralelamente

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Permite execução manual através da UI do GitHub

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Continua executando outros jobs mesmo se um falhar
      matrix:
        containers: [1, 2, 3, 4, 5]
        include:
          - containers: 1
            spec: cypress/e2e/api/products/get.spec.js
          - containers: 2
            spec: cypress/e2e/api/products/post.spec.js
          - containers: 3
            spec: cypress/e2e/api/products/update.spec.js
          - containers: 4
            spec: cypress/e2e/api/products/delete.spec.js
          - containers: 5
            spec: cypress/e2e/api/products/negative.spec.js

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          spec: ${{ matrix.spec }}
          browser: electron
          headed: false

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4 # ← Aqui está a correção
        with:
          name: cypress-results-${{ matrix.containers }}
          path: |
            cypress/reports/
            cypress/screenshots/
          retention-days: 5
